- hosts: localhost
  tasks:
    - name: Get our current IP address for security group
      uri:
        url: http://checkip.amazonaws.com/
        return_content: yes
      register: my_ip

    - name: Create simple security group for wordpress
      ec2_group:
        name: "{{ sg_name }}"
        description: A security group for my current IP
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "{{ my_ip.content | replace('\n', '') }}/32"
      register: wordpress_sg

    - name: Create the ELB
      ec2_elb_lb:
        name: "{{ elb_name }}"
        state: present
        region: "{{ aws_region }}"
        subnets: "{{ subnets }}"
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
        security_group_ids:
          - "{{ wordpress_sg.group_id }}"
      register: wordpress_elb

    - name: Create simple security group for wordpress
      ec2_group:
        name: "{{ ec2_sg_name }}"
        description: A security group for my current IP
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ wordpress_elb.elb.security_group_ids | first }}"
      register: wordpress_ec2_sg

    - name: Create EC2 instances
      ec2:
        key_name: "{{ ec2_keypair }}"
        instance_type: "{{ ec2_instance_type }}"
        image: "{{ ec2_ami_id }}"
        region: "{{ aws_region }}"
        vpc_subnet_id: "{{ item }}"
        group_id:
          - "{{ wordpress_ec2_sg.group_id }}"
        wait: yes
        instance_tags:
          Name: "{{ ec2_name }}"
        exact_count: 1
        count_tag:
          Name: "{{ ec2_name }}"
      with_items: "{{ subnets }}"
      register: ec2_worpress_instances


    - name: Add each EC2 instance to the ELB
      ec2_elb:
        state: present
        ec2_elbs: "{{ elb_name }}"
        region: "{{ item.tagged_instances.0.region }}"
        instance_id: "{{ item.tagged_instances.0.id }}"
      with_items: "{{ ec2_worpress_instances.results }}"
